# Generated by Django 3.2.13 on 2022-06-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_id',
            new_name='res_id',
        ),
    ]
