# Generated by Django 3.2.13 on 2022-06-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservation_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date_created',
        ),
    ]
